object = "fluid.waveform~"
buffer = false
digest = "Visualise audio waveforms and data."
see-also =  ["fluid.waveform~"]
description="A JSUI object for visualising waveforms, feature data, slices and spectrograms."
discussion = """
The fluid.waveform~ object is designed for visualising audio waveforms, feature data, slices and spectrograms. This is a convenient way to interrogate analysis, or visualise the results of processes.
"""

[messages]

[messages.waveform]
msgdesc="Paint a waveform from a buffer."
args = [
    { name="buffer", type="symbol", optional=0 },
    { name="color", type="symbol", optional=1}
]

[messages.features]
msgdesc="Paint a feature curve from a buffer."
args = [
    { name="buffer", type="symbol", optional=0 },
    { name="color", type="symbol", optional=1}
] 

[messages.image]
msgdesc="Construct an image from a two-dimensional buffer~ of values, such as a spectrogram."
args = [
    { name="buffer", type="symbol", optional=0 }
]

[messages.slices]
msgdesc="Paint vertical slices stored in a buffer~ onto the waveform. These markers can be moved, deleted, and added manually too."
args = [
    { name="markers buffer", type="symbol", optional=0 },
    { name="reference", type="symbol", optional=0 },
]

[messages.remove]
msgdesc="Remove a specific layer from the waveform."
args = [
    { name="layer", type="symbol", optional=0 }
]

[messages.clear]
msgdesc="Reset the state of the object."
args=[]

[messages.bgcolor]
msgdesc="Set the background color."
args=[]