digest = "Copy A List To A Buffer"
see-also =  ["fluid.buf2list"]
description = "Copies the values of a list to a buffer."
discussion = """
fluid.list2buf copies the values of a list to a buffer.

This is a convenient way of transforming data such that it can interface with other FluCoMa objects that expect to receive a buffer.

Be aware that if a buffer of a predefined size is not supplied as the output it will defer the copying. If you need the copying to occur in the high priority thread, supply a buffer with the size of the input.
"""

[output]
output = "The name of the buffer~ the list is copied to with the prefix 'buffer'."

[controls]
autosize = "Determines if the output buffer will be resized according to the size of the input list."
axis = """
Changes the orientation of the data that is copied. `axis 0` copies frame-wise into a single channel. `axis 1` will copy the list channel-wise resulting in as many channels as there are elements in the input list.
"""

destination = "The buffer~ to copy the list values to."
startchan = "For multichannel output buffers, which which channel to begin copying to. The default is 0."
startframe = "The starting index (in samples) from which to copy in the source buffer."

[message]
list = "The input list to be copied."


