object = "fluid.waveform"
buffer = false
digest = "Plot fluid.multiarrays in various ways."
see-also =  ["fluid.multiarray"]
description = "A GUI object that plots data from fluid.multiarrays of audio, features, images and indices."
discussion = """
The fluid.waveform object can be used as a versatile solution for plotting arrays and multiarrays.

It plots multichannel audio as waveform.
It plots time-series of features as lines.
It plots images of 2D matrices, i.e. spectrograms.
It plots indices as markers.

See the helpfile for various examples.

"""
[inlets]
[inlets.1]
type="anything"
description="See below for the various messages."

[outlets]
[outlets.1]
type="list"
description="A list of the x-y coordinates where the mouse is clicked and dragged."

[arguments]
[arguments.width]
type="int"
description="The width of the object."
default="10"
optional=false

[arguments.heigth]
type="int"
description="The height of the object."
default="10"
optional=false

[arguments.outline]
type="int"
description="A flag to draw the frame around the object."
default="0"
optional=true

[arguments.send]
type="symbol"
description="The name of the object for receiving messages."
default="empty"
optional=true

[arguments.receive]
type="symbol"
description="The name of the object on which it will send its mousing values."
default="empty"
optional=true

[arguments.latch]
type="int"
description="A flag to send a value on mouse up."
default="0"
optional=true

[attributes]
[attributes.outline]
type="int"
size="1"
description="A flag to draw the frame around the object."
default="0"
optional=true

[attributes.send]
type="symbol"
size="1"
description="The name of the object for receiving messages."
default="empty"
optional=true

[attributes.receive]
type="symbol"
size="1"
description="The name of the object on which it will send its mousing values."
default="empty"
optional=true

[attributes.latch]
type="int"
size="1"
description="A flag to send a value on mouse up."
default="0"
optional=true

[messages]

[messages.waveform]
msgdesc="Set the source 'buffer' for the waveform to draw. This can be a multichannel audiofile and will be normalised across channels."
args = [
    { name="buffer", type="symbol", default="", optional=false, desc='The name of the "fluid.multiarray" to draw as a waveform.' }
]

[messages.features]
msgdesc="Set the source 'buffer' for the features to draw. Each feature is normalised individually."
args = [
    { name="buffer", type="symbol", default="", optional=false, desc='The name of the "fluid.multiarray" to draw as lines of features.' }
]

[messages.image]
msgdesc="Set the source 'buffer' for the image matrix to draw. The minimum is mapped to dark and the maximum is mapped to bright. This is sometimes referred to as a heat map."
args = [
    { name="buffer", type="symbol", default="", optional=false, desc='The name of the "fluid.multiarray" to draw as a 2d matrix.' }
]

[messages.indices]
msgdesc="Set the source 'buffer' for the indices to draw. This needs to happen after the waveform is set in order to define the timeframe of the markers."
args = [
    { name="buffer", type="symbol", default="", optional=0, desc='The name of the array, or multiarray, containing indices to draw as markers.' }
]

[messages.imagelogflag]
msgdesc="Set how the full range of values in the 2d matrix is mapped to color. 0 is linear, 1 is logarithmic."
args = [
    { name="flag", type="int", default="0", optional=false, desc='The flag: 0 is linear, 1 is logarithmic.' }
]

[messages.linewidth]
msgdesc="Set the line width for both the markers of indices and the lines of features."
args = [
    { name="width", type="int", default="2", optional=false, desc='The width of the line.' }
]

[messages.waveformcolor]
msgdesc="Set the colour of the waveform. This is the new Pd colour format #rrggbb where rr,gg,bb are hexadecimal for each RGB component."
args = [
    { name="colour", type="symbol", default="#123456", optional=false, desc='The colour in #RRGGBB format.' }
]

[messages.featurescolor]
msgdesc="Set the colour of the features lines. This is the new Pd colour format #rrggbb where rr,gg,bb are hexadecimal for each RGB component."
args = [
    { name="colour", type="symbol", default="#880000", optional=false, desc='The colour in #RRGGBB format.' }
]

[messages.imagecolorscheme]
msgdesc="Set the perceptually linear color scheme used to draw the matrix values. See the <a href='https://colorcet.com/'>ColorCET website</a> for more information."
args = [
    { name="scheme", type="int", default="0", optional=0, desc='The colour scheme. 0 is CET-L02, 1 is CET-L16.' }
]

[messages.indicescolor]
msgdesc="Set the colour of the marker line drawn for indices. This is the new Pd colour format #rrggbb where rr,gg,bb are hexadecimal for each RGB component."
args = [
    { name="colour", type="symbol", default="#EECC00", optional=false, desc='The colour in #RRGGBB format.' }
]
