object = "fluid.ls2text"
buffer = false
digest = "Convert FluCoMa LabelSet into text"
see-also =  []
description = "A utility object to convert a fluid.labelset into text."
discussion = """
This is an object for conveniently converting a <a href='fluid.labelset.html'>fluid.labelset</a> into text.
"""


[messages]
[messages.bang]
msgdesc="Trigger processing"
args=[]

[arguments]
[arguments.labelset]
type="symbol"
description="A source labelset"
default=""

[arguments.text]
type="symbol"
description="A destination text object"
default=""