object = "fluid.ls2text"
buffer = false
digest = "Convert FluCoMa LabelSet into text"
see-also =  ["fluid.labelset"]
description = "A utility object to convert a fluid.labelset into text."
discussion = """
This is an object for conveniently converting a <a href='fluid.labelset.html'>fluid.labelset</a> into text.
"""

[inlets]
[inlets.1]
type="bang"
description="Bang triggers the process."

[inlets.2]
type="symbol"
description="Change the <a href='fluid.labelset.html'>fluid.labelset</a> that is converted to text."

[outlets]
[outlets.1]
type="bang"
description="Bang when done."

[messages]
[messages.bang]
msgdesc="Trigger processing"

[arguments]
[arguments.labelset]
type="symbol"
description="A source labelset"
default="none"

[arguments.text]
type="symbol"
description="A destination text object"
default="none"