object = "fluid.s2f"
buffer = false
digest = "Convert a symbol into a float"
see-also =  []
description = "Convert a floating point value expressed as a symbol ('string') and output it as a float."
discussion = """
This object does the opposite of sending a float into [makefilename %f]. Note that the symbol needs to be enclosed in double quotes for s2f to work.
"""

[inlets]
[inlets.1]
type="symbol"
description="The symbol to convert to a float."

[outlets]
[outlets.1]
type="float"
description="The converted input as float."

[messages]
[messages.symbol]
msgdesc="Convert the symbol into a float"
