object = "fluid.plotter"
buffer = false
digest = "Plot data in a two-dimensional graph."
see-also =  ["fluid.ds2text", "fluid.ls2text"]
description = "A GUI object that plots data in a two-dimensional graph."
discussion = """
The fluid.plotter object can be used as a versatile solution for plotting points in a two-dimensional graph.

It is designed to easily accept the contents of a fluid.dataset via a dictionary as coordinates within the graph as well as the contents of a fluid.labelset~ via a dictionary as colours for points.

There is also an 'advanced' interface that allows the user to specify the coordinates and colours of the points in a more flexible and bespoke manner. See the help file for more information on this.
"""

[attributes]
[attributes.axis]
digest = "Direction in which to copy from the source<."
description="In what direction to copy data from the source. <m>0</m> copies frame by frame, <m>1</m> copies channel-by-channel."
type = "int"
value = "0"

[attributes.source]
digest = "The buffer~ to copy the values from."
description="Sets the source buffer~ to copy data from."
type = "symbol"

[attributes.startchan]
digest="Start channel in destination."
description="For multichannel input buffers, which channel to begin copying from. The default is 0."
type = "int"
value = "0"

[messages]
[messages.xrange]
msgdesc="Set the x-axis range."
args=[
    { name="min", type="number", desc='The minimum value for the x-axis' },
    { name="max", type="number", desc='The maximum value for the x-axis' }
]

[messages.yrange]
msgdesc ="Set the y-axis range."
args=[
    { name="min", type="number", desc='The minimum value for the y-axis' },
    { name="max", type="number", desc='The maximum value for the y-axis' }
]

[messages.range]
msgdesc = "Set the x- and y-axis ranges."
args=[
    { name="min", type="number", desc='The minimum value for the x-axis and y-axis' },
    { name="max", type="number", desc='The maximum value for the x-axis and y-axis' }
]

[messages.highlight]
msgdesc="Emphasises the given identifier's points in the plot"
args=[
	{ name="identifiers", type="list", desc="Any number of identifiers" }
]

[messages.clear]
msgdesc = "Clears the graph and all associated data and settings."
args = [] 

[messages.setlabels]
msgdesc="Set the labels for each point according to their labels in a fluid.labelset."
args=[
	{ name="text", type="symbol", desc="The name of a text object containing data from a fluid.dataset. This message must enter the left inlet."  }
]

[messages.setpoints]
msgdesc="Set the position for points by their data in a fluid.dataset."
args=[
	{ name="text", type="symbol", desc="The name of a text object containing labels from a fluid.labelset. This message must enter the right inlet."  }
]

