object = "fluid.multiarray"
buffer = false
digest = "Multichannel arrays"
see-also =  []
description = "An abstraction that assists in the management and creation of multichannel arrays."
discussion = """
This abstraction allows the creation of multichannel arrays. Note that it requires invoking with the clone object to work.
"""

[arguments]
[arguments.channels]
type="int"
description="The number of channels for the multiarray"

[arguments.name]
type="symbol"
description="The name of the multiarray"

[arguments.size]
type="int"
description="The number of elements that the array should store"

