object = "fluid.list2buf"
buffer = false
digest = "Copy A List To A Buffer"
see-also =  ["fluid.buf2list"]
description = "Copies the values of a list to a buffer."
discussion = """
fluid.list2buf copies the values of a list to a buffer.

This is a convenient way of transforming data such that it can interface with other FluCoMa objects that expect to receive a buffer.

Be aware that if a buffer of a predefined size is not supplied as the output it will defer the copying. If you need the copying to occur in the high priority thread, supply a buffer with the size of the input.
"""

[attributes]
[attributes.autosize]
digest = "Determines if the output buffer will be resized according to the size of the input list."
description=""
type="int"
size="1"
value="1"

[attributes.axis]
digest = "Changes the orientation of the data that is copied. `axis 0` copies frame-wise into a single channel. `axis 1` will copy the list channel-wise resulting in as many channels as there are elements in the input list."
description=""
type="int"
size="1"
value="0"

[attributes.destination]
digest="The buffer~ to copy the list values to."
description=""
type="symbol"
size="1"

[attributes.startchan]
digest="For multichannel output buffers, which which channel to begin copying to. The default is 0."
description=""
type="int"
size="1"
value="0"

[attributes.startframe]
digest="The starting index (in samples) from which to copy in the source buffer."
description=""
type="int"
size="1"
value="0"

[messages]
[messages.list]
digest = "The input list to be copied."



