object = "fluid.buf2list"
buffer = true
digest = "Copy the contents of a buffer~ to a list"
see-also =  ["fluid.list2buf", "peek~", "poke~"]
description = "A simplified workflow for extracting numerical data from buffers as lists of numbers."
discussion = """
Given a source buffer that is valid, fluid.buf2list copies its contents to a new list when it receives a bang.

This is a convenient way of extracting data from a buffer to be used elsewhere.
"""

[arguments]
[arguments.maxsize]
optional="1"
type="number"
digest="Maximum list size"
description="Sets a maximum size for the internal list. The absolute maximum in Max is 32767."
default = { type="int", size="1", value="256" }

[attributes]
[attributes.axis]
digest = "Direction in which to copy from the <at>source</at>."
description="In what direction to copy data from the <at>source</at>. <m>0</m> copies frame by frame, <m>1</m> copies channel-by-channel."
type = "int"
value = "0"
size = "1"

[attributes.source]
digest = "The <o>buffer~</o> to copy the values from."
description="Sets the source <o>buffer~</o> to copy data from."
type = "symbol"
size = "1"

[attributes.startchan]
digest="Start channel in <at>destination</at>."
description="For multichannel input buffers, which channel to begin copying from. The default is 0."
type = "int"
size = "1"
value = "0"

[attributes.startframe]
digest="Start frame in <at>destination</at>."
description="The starting index (in samples) to copy values from the <at>source</at> <o>buffer~</o>."
type = "int"
size = "1"
value = "0"

[messages]
[messages.bang]
digest="Trigger processing"
description="Copies the contents of the <at>source</at> <o>buffer~</o> to the list."
args=[]


