object = "fluid.audiofilesin"
buffer = false
digest = "Collect audio from a directory"
see-also =  ["fluid.concataudiofiles", "folder"]
description = "A convenience abstraction for collecting all audio files in a directory into a list."
discussion = """
Given a valid path to a directory on disk, this abstraction reports all audio files that Max can open in that directory.
"""

[messages]
[messages.list]
msgdigest="A valid path to a directory"
msgdesc="The directory to scan for audio files."




