object = "fluid.plotter"
buffer = false
digest = "Plot data in a two-dimensional graph."
see-also =  ["fluid.waveform~"]
description = "A JSUI object that plots data in a two-dimensional graph."
discussion = """
The fluid.plotter object can be used as a versatile solution for plotting points in a two-dimensional graph.

It is designed to easily accept the contents of a fluid.dataset~ via a dictionary as coordinates within the graph as well as the contents of a fluid.labelset~ via a dictionary as colours for points.

There is also an 'advanced' interface that allows the user to specify the coordinates and colours of the points in a more flexible and bespoke manner. See the help file for more information on this.
"""

[inlets]
[inlets.0]
type="anything"
digest="A dictionary of coordinates for the points in the graph."
description="The dictionary of coordinates in the correct format for the plotter. By default, the <m>dump</m> method of a <o>fluid.dataset~</o> will work."

[inlets.1]
type="anything"
digest="A dictionary of labels for the points in the graph."
description="The dictionary of labale in the correct format for the plotter. By default, the <m>dump</m> method of a <o>fluid.labelset~</o> will work."

[outlets]
[outlets.0]
type="anything"
digest="The position of the mouse."
description="The position of the mouse will be reported while the mouse is over the plotter and is clicking and dragging. The position is constrained to the domain of the plotter."

[outlets.1]
type="anything"
digest="Zoom updates."
description="Reports any updates made to the plotter view while zooming."

[messages]
[messages.xrange]
msgdesc="Set the x-axis range."
args=[
    { name="min", type="float", default=0, optional=0 },
    { name="max", type="float", default=1, optional=0 }
]

[messages.yrange]
msgdesc ="Set the y-axis range."
args=[
    { name="min", type="float", default=0, optional=0 },
    { name="max", type="float", default=1, optional=0 }
]

[messages.range]
msgdesc = "Set the x- and y-axis ranges."
args=[
    { name="min", type="float", default=0, optional=0 },
    { name="max", type="float", default=1, optional=0 }
]

[messages.colorscheme]
msgdesc = "Change the colour scheme for automatic colouring via a fluid.labelset~. Options are default, cat, accent, dark, paired, tableau, R4, R3, R2, R1, random. Taken mostly from <a href='https://github.com/d3/d3-scale-chromatic'>d3-scale-chromatic</a>."
args = [
    { name="scheme", type="symbol", default="default", optional=0 }
]

[messages.setpoint]
msgdesc = "Set the point at the given coordinates."
args = [
    { name="identifier", type="symbol", optional=0 },
    { name="x", type="float", optional=0 },
    { name="y", type="float", optional=0 },
]

[messages.pointcolor]
msgdesc = "Set the color of the point with a given identifier."
args = [
    { name="identifier", type="symbol", optional=0 },
    { name="red", type="float", optional=0 },
    { name="green", type="float", optional=0 },
    { name="blue", type="float", optional=0 },
    { name="alpha", type="float", optional=0 }
]

[messages.pointsize]
msgdesc = "Set the size of the point with a given identifier."
args = [
    { name="identifier", type="symbol", optional=0 },
    { name="size", type="float", optional=0 }
]

[messages.pointsizescale]
msgdesc = "Set the overall size of the points."
args = [
    { name="scale", type="float", optional=0 }
]

[messages.shape]
msgdesc = "Modifies the shape of the points."
args = [
    { name="shape", type="symbol", optional=0 }
]

[messages.clear]
msgdesc = "Clears the graph and all associated data and settings."
args = []

[messages.reset]
msgdesc = "An alias of clear. Clears the graph."
args = []